eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.245:8080/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign   

    
jedis :  
  pool :  
<<<<<<< HEAD
    host : 172.16.4.218
    port : 6379
=======
    host : 192.168.1.245
    port : 6379  
>>>>>>> refs/remotes/origin/master
    config :  
      maxTotal: 100  
      maxIdle: 10  
      maxWaitMillis : 100000           
      
      
      

      